export type CURRENCY_PAIR = CURRENCY_PAIRS[number]
export type CURRENCY_PAIRS = typeof CURRENCY_PAIRS
export const CURRENCY_PAIRS = [
	"EUR_USD",
	"GBP_USD",
	"USD_CAD",
	"USD_CHF",
	"USD_JPY",
	"EUR_GBP",
	"EUR_CHF",
	"AUD_USD",
	"EUR_JPY",
	"GBP_JPY",
	"EUR_AUD",
	"EUR_CZK",
	"EUR_HUF",
	"EUR_NZD",
	"EUR_SEK",
	"EUR_SGD",
	"EUR_CAD",
	"EUR_DKK",
	"EUR_NOK",
	"EUR_PLN",
	"EUR_TRY",
	"EUR_ZAR",
	"USD_CNH",
	"USD_DKK",
	"USD_HUF",
	"USD_MXN",
	"USD_PLN",
	"USD_SEK",
	"USD_THB",
	"USD_ZAR",
	"USD_CZK",
	"USD_HKD",
	"USD_NOK",
	"USD_SGD",
	"USD_TRY",
	"GBP_AUD",
	"GBP_CHF",
	"GBP_ZAR",
	"GBP_SGD",
	"AUD_JPY",
	"AUD_SGD",
	"CAD_JPY",
	"CHF_JPY",
	"NZD_CAD",
	"NZD_USD",
	"SGD_JPY",
	"ZAR_JPY",
	"GBP_CAD",
	"GBP_NZD",
	"GBP_PLN",
	"AUD_CAD",
	"AUD_NZD",
	"CAD_CHF",
	"CAD_SGD",
	"CHF_ZAR",
	"NZD_JPY",
	"NZD_SGD",
	"TRY_JPY"
] as const

export type CURRENCY = CURRENCIES[number]
export type CURRENCIES = typeof CURRENCIES
export const CURRENCIES = [
	"SGD",
	"EUR",
	"USD",
	"GBP",
	"CAD",
	"CHF",
	"JPY",
	"AUD",
	"CZK",
	"HUF",
	"NZD",
	"SEK",
	"DKK",
	"NOK",
	"PLN",
	"TRY",
	"ZAR",
	"CNH",
	"HKD",
	"THB",
	"MXN"
] as const

export type FXEMPIRE_COUNTRIES = typeof FXEMPIRE_COUNTRIES
export const FXEMPIRE_COUNTRIES = {
	SGD: "singapore",
	EUR: "euro-area",
	USD: "united-states",
	GBP: "united-kingdom",
	CAD: "canada",
	CHF: "switzerland",
	JPY: "japan",
	AUD: "australia",
	CZK: "czech-republic",
	HUF: "hungary",
	NZD: "new-zealand",
	SEK: "sweden",
	DKK: "denmark",
	NOK: "norway",
	PLN: "poland",
	TRY: "turkey",
	ZAR: "south-africa",
	CNH: "china",
	HKD: "hong-kong",
	THB: "thailand",
	MXN: "mexico"
} as const

export type CURRENCY_FLAGS = typeof CURRENCY_FLAGS
export const CURRENCY_FLAGS = {
	SGD: "https://flagicons.lipis.dev/flags/4x3/sg.svg",
	EUR: "https://flagicons.lipis.dev/flags/4x3/eu.svg",
	USD: "https://flagicons.lipis.dev/flags/4x3/us.svg",
	GBP: "https://flagicons.lipis.dev/flags/4x3/gb.svg",
	CAD: "https://flagicons.lipis.dev/flags/4x3/ca.svg",
	CHF: "https://flagicons.lipis.dev/flags/4x3/ch.svg",
	JPY: "https://flagicons.lipis.dev/flags/4x3/jp.svg",
	AUD: "https://flagicons.lipis.dev/flags/4x3/au.svg",
	CZK: "https://flagicons.lipis.dev/flags/4x3/cz.svg",
	HUF: "https://flagicons.lipis.dev/flags/4x3/hu.svg",
	NZD: "https://flagicons.lipis.dev/flags/4x3/nz.svg",
	SEK: "https://flagicons.lipis.dev/flags/4x3/se.svg",
	DKK: "https://flagicons.lipis.dev/flags/4x3/dk.svg",
	NOK: "https://flagicons.lipis.dev/flags/4x3/no.svg",
	PLN: "https://flagicons.lipis.dev/flags/4x3/pl.svg",
	TRY: "https://flagicons.lipis.dev/flags/4x3/tr.svg",
	ZAR: "https://flagicons.lipis.dev/flags/4x3/za.svg",
	CNH: "https://flagicons.lipis.dev/flags/4x3/cn.svg",
	HKD: "https://flagicons.lipis.dev/flags/4x3/hk.svg",
	THB: "https://flagicons.lipis.dev/flags/4x3/th.svg",
	MXN: "https://flagicons.lipis.dev/flags/4x3/mx.svg"
} as const
